### ISSUE TITLE
can't connect to AWS elasticsearch (6.7)

### ISSUE THREAD

**Issue by asloan7** [kiwigrid/helm-charts#152]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Which chart in which version**:
apiVersion: v1
name: fluentd-elasticsearch
version: 4.4.0
appVersion: 2.6.0

**What happened**:
fluentd-elasticsearch-2.6.0]$ kubectl logs -n logging fluentd-elasticsearch-787zj
2019-07-25 14:43:30 +0000 [error]: unexpected error error_class=Elasticsearch::Transport::Transport::Errors::Forbidden error="[403] {\"Message\":\"User: anonymous is not authorized to perform: es:ESHttpGet\"}"
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/base.rb:338:in `perform_request'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/client.rb:160:in `perform_request'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/elasticsearch-api-7.1.0/lib/elasticsearch/api/actions/info.rb:32:in `info'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:334:in `detect_es_major_version'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:245:in `block in configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:244:in `configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/plugin.rb:164:in `configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/agent.rb:130:in `add_match'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/agent.rb:72:in `block in configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/agent.rb:64:in `each'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/agent.rb:64:in `configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/root_agent.rb:150:in `configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/engine.rb:131:in `configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/engine.rb:96:in `run_configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/supervisor.rb:801:in `run_configure'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/supervisor.rb:548:in `block in run_worker'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/supervisor.rb:730:in `main_process'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/supervisor.rb:544:in `run_worker'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2019-07-25 14:43:30 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-07-25 14:43:30 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-07-25 14:43:30 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/bin/fluentd:8:in `<top (required)>'
  2019-07-25 14:43:30 +0000 [error]: /usr/local/bin/fluentd:22:in `load'
  2019-07-25 14:43:30 +0000 [error]: /usr/local/bin/fluentd:22:in `<main>'

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by asloan7** [comment]
For comparison with older version:

**Comment by asloan7** [comment]
Sorry, AWS elasticsearch policy typo was causing this
