### ISSUE TITLE
1 pod fails to connect to AWS ES

### ISSUE THREAD

**Issue by angegar** [kiwigrid/helm-charts#63]
**Is this a request for help?**:
Yes it is
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:41:50Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Which chart in which version**:

fluentd-elasticsearch-2.7.0             2.4.0       

**What happened**:
1 pods does not manage to send log to AWS Elasticsearch when the 2 others sounds to work perfectly

**What you expected to happen**:
All the pods works like a charm

**How to reproduce it** (as minimally and precisely as possible):
I just deploy the chart on my kubernetes stack with the default values.yml file configured to target my AWS ES database

**Anything else we need to know**:
I added the 3 following configuration to the AWS ES match : 
      resurrect_after 5s
      reload_on_failure true
      reload_connections false

Please find below the log file from the unhealthy pod :

```
2019-03-26 14:24:18 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Exception encountered fetching metadata from Kubernetes API endpoint: pods is forbidden: User \"system:serviceaccount:monitoring:fluentd-monitoring-fluentd-elasticsearch\" cannot list pods at the cluster scope ({\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"pods is forbidden: User \\\"system:serviceaccount:monitoring:fluentd-monitoring-fluentd-elasticsearch\\\" cannot list pods at the cluster scope\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"pods\"},\"code\":403}\n)"
```

**Comment by monotek** [comment]
Do you have rbac disabled?
If enabled, the right to list pods is set. 
See: https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/templates/clusterrole.yaml#L22

**Comment by angegar** [comment]
it is enabled.

**Comment by angegar** [comment]
What is weard is that it seems to work for 2 pods but the third one fails.

BTW thank you for your help, i just my all working day on it and i am lost 😪

**Comment by angegar** [comment]
Can you please explain to me where / how the service account is used ?

**Comment by angegar** [comment]
After 59 retries the pods seems to work, when i look into the logs i found the following warnings : 

```
2019-03-27 03:10:32 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=0 next_retry_seconds=2019-03-27 03:10:33 +0000 chunk="5850ac739e319a6c79235be9840c1d39" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"***.us-east-1.es.amazonaws.com\", :port=>443, :scheme=>\"https\"}): read timeout reached"
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:655:in `rescue in send_bulk'
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:638:in `send_bulk'
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:544:in `block in write'
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:543:in `each'
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.2/lib/fluent/plugin/out_elasticsearch.rb:543:in `write'
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1123:in `try_flush'
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2019-03-27 03:10:32 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-03-27 03:10:32 +0000 [warn]: [elasticsearch] retry succeeded. chunk_id="5850ac74c4dcb9400d3b7069988f0fdc"
```
