### ISSUE TITLE
fluentd fails and restarts all the time

### ISSUE THREAD

**Issue by Sanjanare** [kiwigrid/helm-charts#85]
Hi i get the following error when i install fluentd on k8s which talks to Aws ES, logs go fine but the fluentd restarts all the time:

>>> 2019-05-02 19:53:59 +0000 [warn]: dump an error event: error_class=Fluent::Plugin::ConcatFilter::TimeoutError error="Timeout flush: kernel:default" location=nil tag="kernel" time=2019-05-02 19:53:59.814288919 +0000 record={"priority"=>"6", "boot_id"=>"896d98e4770742679351613906e814ab", "machine_id"=>"ec2e1846d08b4dce48cb0784eee1afc3", "hostname"=>"ip-10-104-127-75", "transport"=>"kernel", "syslog_facility"=>"0", "syslog_identifier"=>"kernel", "message"=>"cbr0: port 5(veth8260447c) entered disabled statedevice veth8260447c left promiscuous modecbr0: port 5(veth8260447c) entered disabled state", "source_monotonic_timestamp"=>"1226774483531"}
2019-05-02 20:06:07 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=0 next_retry_seconds=2019-05-02 20:06:08 +0000 chunk="587ed298f69c6778a968deab34cbc42d" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"localhost\", :port=>8080, :scheme=>\"http\", :user=>\"\", :password=>\"obfuscated\"}): read timeout reached"
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.3.3/lib/fluent/plugin/out_elasticsearch.rb:703:in `rescue in send_bulk'
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.3.3/lib/fluent/plugin/out_elasticsearch.rb:679:in `send_bulk'
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.3.3/lib/fluent/plugin/out_elasticsearch.rb:585:in `block in write'
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.3.3/lib/fluent/plugin/out_elasticsearch.rb:584:in `each'
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.3.3/lib/fluent/plugin/out_elasticsearch.rb:584:in `write'
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.4.1/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.4.1/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.4.1/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-05-02 20:06:07 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.4.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-05-02 20:06:08 +0000 [warn]: [elasticsearch] retry succeeded. chunk_id="587ed299eae2e26c8bcfd7d4cd9a595d"
2019-05-02 20:08:49 +0000 [warn]: dump an error event: error_class=Fluent::Plugin::ConcatFilter::TimeoutError error="Timeout flush: kernel:default" location=nil tag="kernel" time=2019-05-02 20:08:49.814133959 +0000 record={"priority"=>"6", "boot_id"=>"896d98e4770742679351613906e814ab", "machine_id"=>"ec2e1846d08b4dce48cb0784eee1afc3", "hostname"=>"ip-*******", "transport"=>"kernel", "syslog_facility"=>"0", "syslog_identifier"=>"kernel", "message"=>"cbr0: port 2(vethece8768c) entered disabled statedevice vethece8768c left promiscuous modecbr0: port 2(vethece8768c) entered disabled state", "source_monotonic_timestamp"=>"1227663843094"}

Can some one help me in this?

**Comment by monotek** [comment]
Sorry for not answering earlier. Did you find a solution?

**Comment by Sanjanare** [comment]
we found a bug in the chart and sent a MR , bug was:-  correct container so aws proxy does not keep getting terminated.

**Comment by monotek** [comment]
Which PR are you referring to?
Link?

**Comment by Sanjanare** [comment]
@monotek https://github.com/kiwigrid/helm-charts/pull/88

**Comment by kish2010** [comment]
Hi, I am also getting the same error while loading the data into the kibana.
Error:-
#0 dump an error event: error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster
read timeout reached" location="/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-elasticsearch-4.0.7/lib/fluent/plugin/out_elasticsearch.rb:978:in `rescue in send_bulk'"
